version: '3.4'
services:
  consumer-kafka-node:
    container_name: consumer-kafka-node.flags
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
    networks:
      - bubble

networks:
  bubble:
    external: true

